mqAuth:
  image: develar/java:8u45
  environment:
    # -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5050
    _JAVA_OPTIONS: "-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.impl.SLF4JLogDelegateFactory
      -Dorg.slf4j.simpleLogger.defaultLogLevel=info
      -Dorg.slf4j.simpleLogger.showThreadName=false
      -Xms48m -Xmx64M"
    CLASSPATH: /app/lib/*:/app/classes
    MANAGEMENT_USER: admin
    HUB_PORT: 80
  volumes:
    - out/production/mq-auth:/app/classes:ro
    - lib:/app/lib:ro
    - certs/cert.pem:/cert.pem:ro
  command: org.jetbrains.httpServer.HttpServerPackage
  links:
   - hub
  expose:
   - "80"
#  ports:
#    - "5050:5050"
mq:
  image: cloudintellij/rabbitmq-auth
  # https://github.com/docker-library/rabbitmq/issues/6 I have no idea how it will be going in a Tutum.
  hostname: flux
  links:
    - mqAuth:mq-auth
  volumes:
    - certs:/certs
  ports:
    - "5671:5671"
    # web stomp
    - "4443:4443"
    # management
    - "15672:15672"
hub:
  image: develar/jetpass
  volumes:
    - jetpass-data:/data