mqAuth:
  image: develar/java:8u45
  environment:
    # -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5050
    _JAVA_OPTIONS: "-Dio.netty.machineId=9e43d860 -Xms48m -Xmx64M"
    CLASSPATH: /app/lib/kotlin-runtime.jar:/app/moduleLib/netty-all-4.1.0.Beta5.jar:/app/classes
    MANAGEMENT_USER: admin
    DEV_USER_NAME: "6ff87f46-e7e6-4d94-9066-eedffc8125c6"
    DEV_USER_TOKEN: 42
  volumes:
    - out/production/mq-auth:/app/classes:ro
    - jvm-flux-client/lib:/app/lib:ro
    - mq-auth/lib:/app/moduleLib:ro
  command: org.jetbrains.flux.mqAuth.MqAuthPackage
  expose:
   - "80"
#  ports:
#    - "5050:5050"
mq:
  image: cloudintellij/rabbitmq-auth
  # https://github.com/docker-library/rabbitmq/issues/6 I have no idea how it will be going in a Tutum.
  hostname: flux
  links:
    - mqAuth:mq-auth
  volumes:
    - certs:/certs
  ports:
    - "5671:5671"
    # web stomp
    - "4443:4443"
    # management
    - "15672:15672"
hub:
  image: develar/jetpass
  environment:
    _JAVA_OPTIONS: "-Xms48m -Xmx64M -Djetbrains.jetpass.database.location=/data/data"
  volumes:
    - jetpass-data:/data